version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  db:
