version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
        name: which bundler?
        command: bundle -v
      - ruby/bundle-install
